---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
