apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  selector:
    app: monitor
  ports:
    - name: metrics
      port: 9253
      targetPort: 8000
      protocol: TCP
